/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 ./public/models/torii/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Torii(props) {
  const { nodes, materials } = useGLTF('./models/torii/model.glb ')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1663585988.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1955180762.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1550870799.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group247445190.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1710676761.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1620146056.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group680338017.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1031386602.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1978873540.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group608985182.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group253099935.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group573006516.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group430518314.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group161610501.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1686182310.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1835582437.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group978197033.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group444571545.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1008993683.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1065523258.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group504911696.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group681307663.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1986319060.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group550662795.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1622620226.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1173417997.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1773656768.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1582756720.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1264546037.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group983689028.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group78794178.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group2114051451.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group980551673.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1576586476.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group396645464.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group247915387.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group68363817.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group719265100.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1549020050.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group910149262.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group539514273.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1759264530.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1546947500.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group328630949.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group679819663.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group928867051.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group933108456.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group439693478.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1734191189.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1710753602.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group276804305.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1562799948.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group828070390.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1352686421.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh2112404912.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh2112404912_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh674213820.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh674213820_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh674213820_2.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh2102673328.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh2102673328_1.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh1119409316.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1119409316_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1119409316_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh467616785.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh467616785_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh467616785_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1738134039.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1738134039_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1738134039_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1112741560.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1112741560_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1112741560_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1771167811.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1771167811_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1771167811_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1190821758.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1190821758_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1190821758_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1880701193.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1880701193_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1880701193_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh729000303.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh729000303_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh729000303_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1342856348.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1342856348_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1342856348_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1696188762.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1696188762_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1696188762_2.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1997551359.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1997551359_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1997551359_2.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh711260887.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh711260887_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh711260887_2.geometry} material={materials.mat8} />
    </group>
  )
}

useGLTF.preload('./models/torii/model.glb ')
